# fly.toml

app = "snippets"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  DATABASE_PATH = "/data/database.sqlite"

[deploy]
  release_command = "npm run register"

[processes]
  app = "npm run start"

[mounts]
  source="snippets_data"
  destination="/data"