# fly.toml

app = "snippets"
primary_region = "fra"

[build]
  builder = "fly-apps/bun"

[env]
  DATABASE_PATH = "/data/database.sqlite"

[deploy]
  release_command = "bun run register"

[processes]
  app = "bun run start"

[mounts]
  source="snippets_data"
  destination="/data"